services:
    firefox:
        image: gtinfosec/firefox
        restart: always
        # Allocate sufficient memory to the Firefox GUI process.
        # If your machine is running out of memory, you might try decreasing this,
        # though Firefox may run into instability if you do so.
        shm_size: 2g
        # Access browser via http://localhost:3235 in your browser
        ports:
            - 3235:5800
            - 3236:5900
        volumes:
            - ..:/workspaces/web
    stealer:
        build: .
        volumes:
            - ..:/workspaces/web
        # Prevent container from instantly exiting, allowing us to attach terminal
        command: /bin/sh -c "sleep infinity"
